name: project-check

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install
        run: make install

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
